# Generated by Django 5.2.4 on 2025-07-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspeccionLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100)),
                ('estado_general', models.CharField(max_length=100)),
                ('observaciones', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
