# Generated by Django 5.2.4 on 2025-08-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspeccionLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea_transmision', models.CharField(max_length=20)),
                ('terna', models.CharField(default='-', max_length=10)),
                ('fecha', models.DateField()),
                ('numero_torre', models.CharField(default='-', max_length=20)),
                ('pintura', models.CharField(choices=[('C', 'Correctivo'), ('P', 'Preventivo'), ('N/M', 'No requiere mantenimiento')], default='-', max_length=20)),
                ('estructuras', models.CharField(choices=[('C', 'Correctivo'), ('P', 'Preventivo'), ('N/M', 'No requiere mantenimiento')], default='-', max_length=20)),
                ('fundaciones', models.CharField(choices=[('C', 'Correctivo'), ('P', 'Preventivo'), ('N/M', 'No requiere mantenimiento')], default='-', max_length=20)),
                ('pernos', models.CharField(choices=[('C', 'Correctivo'), ('P', 'Preventivo'), ('N/M', 'No requiere mantenimiento')], default='-', max_length=20)),
                ('conductor', models.CharField(choices=[('C', 'Correctivo'), ('P', 'Preventivo'), ('N/M', 'No requiere mantenimiento')], default='-', max_length=20)),
                ('aisladores', models.CharField(choices=[('C', 'Correctivo'), ('P', 'Preventivo'), ('N/M', 'No requiere mantenimiento')], default='-', max_length=20)),
                ('herrajes', models.CharField(choices=[('C', 'Correctivo'), ('P', 'Preventivo'), ('N/M', 'No requiere mantenimiento')], default='-', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
    ]
