# Generated by Django 5.2.4 on 2025-07-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineas_transmision', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspeccionlinea',
            old_name='estado_general',
            new_name='linea_transmision',
        ),
        migrations.RemoveField(
            model_name='inspeccionlinea',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='inspeccionlinea',
            name='acceso',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inspeccionlinea',
            name='amortiguadores_estado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inspeccionlinea',
            name='arreglo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inspeccionlinea',
            name='corrosion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inspeccionlinea',
            name='empalme_estado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inspeccionlinea',
            name='estado_aislador',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inspeccionlinea',
            name='fases_estado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inspeccionlinea',
            name='ferreteria_torre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inspeccionlinea',
            name='fundaciones',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inspeccionlinea',
            name='grado_ensuciamiento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inspeccionlinea',
            name='lado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inspeccionlinea',
            name='material_aislador',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inspeccionlinea',
            name='numero_cadenas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspeccionlinea',
            name='numero_torre',
            field=models.CharField(default='000', max_length=20),
        ),
        migrations.AddField(
            model_name='inspeccionlinea',
            name='pintura',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inspeccionlinea',
            name='servidumbre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspeccionlinea',
            name='terna',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspeccionlinea',
            name='tipo_torre',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AlterField(
            model_name='inspeccionlinea',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='inspeccionlinea',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
