# Generated by Django 5.2.4 on 2025-08-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineas_transmision', '0002_rename_estado_general_inspeccionlinea_linea_transmision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspeccionlinea',
            name='acceso',
        ),
        migrations.RemoveField(
            model_name='inspeccionlinea',
            name='amortiguadores_estado',
        ),
        migrations.RemoveField(
            model_name='inspeccionlinea',
            name='arreglo',
        ),
        migrations.RemoveField(
            model_name='inspeccionlinea',
            name='corrosion',
        ),
        migrations.RemoveField(
            model_name='inspeccionlinea',
            name='empalme_estado',
        ),
        migrations.RemoveField(
            model_name='inspeccionlinea',
            name='estado_aislador',
        ),
        migrations.RemoveField(
            model_name='inspeccionlinea',
            name='fases_estado',
        ),
        migrations.RemoveField(
            model_name='inspeccionlinea',
            name='ferreteria_torre',
        ),
        migrations.RemoveField(
            model_name='inspeccionlinea',
            name='grado_ensuciamiento',
        ),
        migrations.RemoveField(
            model_name='inspeccionlinea',
            name='lado',
        ),
        migrations.RemoveField(
            model_name='inspeccionlinea',
            name='material_aislador',
        ),
        migrations.RemoveField(
            model_name='inspeccionlinea',
            name='numero_cadenas',
        ),
        migrations.RemoveField(
            model_name='inspeccionlinea',
            name='servidumbre',
        ),
        migrations.RemoveField(
            model_name='inspeccionlinea',
            name='tipo_torre',
        ),
        migrations.AddField(
            model_name='inspeccionlinea',
            name='aisladores',
            field=models.CharField(choices=[('C', 'Correctivo'), ('P', 'Preventivo'), ('-', 'No requiere mantenimiento')], default='OK', max_length=1),
        ),
        migrations.AddField(
            model_name='inspeccionlinea',
            name='conductor',
            field=models.CharField(choices=[('C', 'Correctivo'), ('P', 'Preventivo'), ('-', 'No requiere mantenimiento')], default='OK', max_length=1),
        ),
        migrations.AddField(
            model_name='inspeccionlinea',
            name='estructuras',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspeccionlinea',
            name='herrajes',
            field=models.CharField(choices=[('C', 'Correctivo'), ('P', 'Preventivo'), ('-', 'No requiere mantenimiento')], default='OK', max_length=1),
        ),
        migrations.AddField(
            model_name='inspeccionlinea',
            name='pernos',
            field=models.CharField(choices=[('C', 'Correctivo'), ('P', 'Preventivo'), ('-', 'No requiere mantenimiento')], default='OK', max_length=1),
        ),
        migrations.AlterField(
            model_name='inspeccionlinea',
            name='fundaciones',
            field=models.CharField(choices=[('C', 'Correctivo'), ('P', 'Preventivo'), ('-', 'No requiere mantenimiento')], default='OK', max_length=1),
        ),
        migrations.AlterField(
            model_name='inspeccionlinea',
            name='numero_torre',
            field=models.CharField(default='OK', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspeccionlinea',
            name='pintura',
            field=models.CharField(choices=[('C', 'Correctivo'), ('P', 'Preventivo'), ('-', 'No requiere mantenimiento')], default='OK', max_length=1),
        ),
        migrations.AlterField(
            model_name='inspeccionlinea',
            name='terna',
            field=models.CharField(default='OK', max_length=50),
        ),
    ]
