# Generated by Django 5.2.4 on 2025-08-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineas_transmision', '0003_remove_inspeccionlinea_acceso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccionlinea',
            name='aisladores',
            field=models.CharField(choices=[('C', 'Correctivo'), ('P', 'Preventivo'), ('-', 'No requiere mantenimiento')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspeccionlinea',
            name='conductor',
            field=models.CharField(choices=[('C', 'Correctivo'), ('P', 'Preventivo'), ('-', 'No requiere mantenimiento')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspeccionlinea',
            name='estructuras',
            field=models.CharField(choices=[('C', 'Correctivo'), ('P', 'Preventivo'), ('-', 'No requiere mantenimiento')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspeccionlinea',
            name='fundaciones',
            field=models.CharField(choices=[('C', 'Correctivo'), ('P', 'Preventivo'), ('-', 'No requiere mantenimiento')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspeccionlinea',
            name='herrajes',
            field=models.CharField(choices=[('C', 'Correctivo'), ('P', 'Preventivo'), ('-', 'No requiere mantenimiento')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspeccionlinea',
            name='linea_transmision',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inspeccionlinea',
            name='numero_torre',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspeccionlinea',
            name='pernos',
            field=models.CharField(choices=[('C', 'Correctivo'), ('P', 'Preventivo'), ('-', 'No requiere mantenimiento')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspeccionlinea',
            name='pintura',
            field=models.CharField(choices=[('C', 'Correctivo'), ('P', 'Preventivo'), ('-', 'No requiere mantenimiento')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspeccionlinea',
            name='terna',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
