# Generated by Django 5.2.4 on 2025-07-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspeccionTransformador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('subestacion', models.CharField(max_length=100)),
                ('transformadr', models.CharField(max_length=100)),
                ('nivel_aceite', models.CharField(max_length=50)),
                ('estado_general', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
