# Generated by Django 5.2.4 on 2025-07-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformadores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspecciontransformador',
            old_name='transformadr',
            new_name='transformador',
        ),
        migrations.AlterField(
            model_name='inspecciontransformador',
            name='estado_general',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inspecciontransformador',
            name='observaciones',
            field=models.TextField(),
        ),
    ]
