# Generated by Django 5.2.4 on 2025-08-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformadores', '0003_remove_inspecciontransformador_nivel_aceite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspecciontransformador',
            name='chequeo_de_circuitos_de_control',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspecciontransformador',
            name='contador_de_descarga_de_pararrayos',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspecciontransformador',
            name='control_de_silica_gel',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspecciontransformador',
            name='estado_de_aisladores',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspecciontransformador',
            name='estado_de_pararrayos',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspecciontransformador',
            name='estado_funcionamiento_ventiladores',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspecciontransformador',
            name='fugas_de_aceite',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspecciontransformador',
            name='indicador_de_cambio_de_tap_en_area_sombreada',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspecciontransformador',
            name='limpieza_de_radiadores',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspecciontransformador',
            name='limpieza_de_transformadores',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspecciontransformador',
            name='nivel_aceite_conmutador',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspecciontransformador',
            name='nivel_aceite_tanque',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspecciontransformador',
            name='nivel_de_aceite_bushings',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspecciontransformador',
            name='numero_de_operaciones_del_cambiador_de_taps',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspecciontransformador',
            name='oxido_y_corrosión',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspecciontransformador',
            name='pintura',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspecciontransformador',
            name='posición_de_taps',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspecciontransformador',
            name='revisión_de_conexiones_a_tierra',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspecciontransformador',
            name='subestacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inspecciontransformador',
            name='temperatura_aceite',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AlterField(
            model_name='inspecciontransformador',
            name='temperatura_devanado',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AlterField(
            model_name='inspecciontransformador',
            name='tipo_transformador',
            field=models.CharField(choices=[('TR1', 'MT1 300MVA'), ('TR2', 'MT2 300MVA'), ('TR3', 'IP T-1 50 MVA')], default='TR1', max_length=4),
        ),
        migrations.AlterField(
            model_name='inspecciontransformador',
            name='vibracion_ruido',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
