# Generated by Django 5.2.4 on 2025-08-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformadores', '0004_alter_inspecciontransformador_chequeo_de_circuitos_de_control_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspecciontransformador',
            name='estado_general',
            field=models.CharField(max_length=20),
        ),
    ]
